version: '3.4'

services:
  mongodb_api:
    image: nodejs_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
