version: '3.4'

services:
  redis_api:
    image: nodejs_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/db
volumes:
 redis_data:
